#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    compatiblity-check-web-80-http:
      entrypoints:
        - http-33000
      rule: HostRegexp(`^compatiblity-check\.ddev\.site$`)
      
      service: "compatiblity-check-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "compatiblity-check-redirectHttps"
    compatiblity-check-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^compatiblity-check\.ddev\.site$`)
      
      service: "compatiblity-check-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "compatiblity-check-redirectHttps"
    compatiblity-check-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^compatiblity-check\.ddev\.site$`)
      
      service: "compatiblity-check-xhgui-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "compatiblity-check-redirectHttps"
    
    
    
    compatiblity-check-web-80-https:
      entrypoints:
        - http-33001
      rule: HostRegexp(`^compatiblity-check\.ddev\.site$`)
      
      service: "compatiblity-check-web-80"
      ruleSyntax: v3
      
      tls: true
      
    compatiblity-check-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^compatiblity-check\.ddev\.site$`)
      
      service: "compatiblity-check-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    
    compatiblity-check-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^compatiblity-check\.ddev\.site$`)
      
      service: "compatiblity-check-xhgui-80"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    compatiblity-check-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    compatiblity-check-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-compatiblity-check-web:80
        
    compatiblity-check-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-compatiblity-check-web:8025
        
    
    
    compatiblity-check-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-compatiblity-check-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/compatiblity-check.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/compatiblity-check.key